const CONSTANTS_CORE = {
    GAME_WIDTH:  800,
    GAME_HEIGHT: 600,
    COMBAT_ARENA_RADIUS: 400,

    PLAYER_STARTING_SHIPS:   3,
    PLAYER_STARTING_CREDITS: 500,

    SCREEN_TRANSITION_TIME:      300,
    CREDITS_PER_ENEMY_DESTROYED: 100,
};
