const CONSTANTS_SHIPS = {
    // Stat ranges — midpoint ~10 for laser/engine/radar, ~25 for hull/shields
    SHIP_STATS: {
        HULL_MIN:    40,
        HULL_MAX:    60,
        SHIELDS_MIN: 20,
        SHIELDS_MAX: 30,
        LASER_MIN:    8,
        LASER_MAX:   12,
        RADAR_MIN:    8,
        RADAR_MAX:   12,
        ENGINE_MIN:   8,
        ENGINE_MAX:  12,
    },

    // Ship types: stat multipliers + normalized polygon vertices (pointing +X, scaled by SHIP_SIZE)
    // internal: true types are excluded from station offers and random generation
    SHIP_TYPES: [
        {
            type: 'Fighter',
            description: 'Fast, agile and hits hard, but fragile. Built-in Chaingun Mount lets it shred enemy hulls with rapid-fire bursts that bypass shields entirely.',
            sizeMult: 0.80, cargoCapacity: 1,
            hullMult: 0.8, shieldMult: 0.7, laserMult: 1.3, radarMult: 1.1, engineMult: 1.4,
            builtinModules: ['chaingun_mount'],
            vertices: [[2.2, 0], [0.2, -1.0], [-0.6, -1.4], [-1.2, -0.4], [-1.2, 0.4], [-0.6, 1.4], [0.2, 1.0]],
        },
        {
            type: 'Freighter',
            description: 'Massive armored hauler repurposed for combat. Near-indestructible hull and shields, but painfully slow. Built-in Debris Launcher turns its cargo hold into a scattershot weapon.',
            sizeMult: 1.40, cargoCapacity: 3,
            hullMult: 1.8, shieldMult: 1.5, laserMult: 0.7, radarMult: 0.8, engineMult: 0.6,
            builtinModules: ['debris_launcher'],
            vertices: [[1.2, 0], [0.8, -1.0], [-0.3, -1.4], [-1.5, -1.2], [-1.5, 1.2], [-0.3, 1.4], [0.8, 1.0]],
        },
        {
            type: 'Raider',
            description: 'Aggressive hit-and-run predator with heavy weapons and strong engines. Built-in Cloak Drive lets it vanish between attacks, striking from the dark.',
            sizeMult: 1.00, cargoCapacity: 1,
            hullMult: 0.9, shieldMult: 0.6, laserMult: 1.4, radarMult: 1.0, engineMult: 1.3,
            builtinModules: ['cloak_drive'],
            vertices: [[2.3, 0], [0.3, -1.0], [-1.8, -1.5], [-1.3, 0], [-1.8, 1.5], [0.3, 1.0]],
        },
        {
            type: 'Corvette',
            description: 'A well-rounded warship with solid hull, shields, and firepower. Built-in Combat AI gives a 25% chance of a bonus action each turn — reliable, adaptable, and always ready.',
            sizeMult: 1.10, cargoCapacity: 1,
            hullMult: 1.2, shieldMult: 1.2, laserMult: 1.0, radarMult: 0.9, engineMult: 0.9,
            builtinModules: ['combat_ai'],
            vertices: [[1.8, 0], [1.2, -0.6], [0.4, -1.3], [-0.6, -1.3], [-1.5, -0.5], [-1.5, 0.5], [-0.6, 1.3], [0.4, 1.3], [1.2, 0.6]],
        },
        {
            type: 'Scout',
            description: 'Extreme speed above everything else. Very fragile but nearly impossible to pin down. Built-in Afterburner lets it cross the field in a single burst, damaging anything in its path.',
            sizeMult: 0.75, cargoCapacity: 1,
            hullMult: 0.6, shieldMult: 0.5, laserMult: 0.8, radarMult: 1.2, engineMult: 1.8,
            builtinModules: ['afterburner_drive'],
            vertices: [[3.0, 0], [0.5, -0.3], [-0.2, -0.9], [-1.5, -0.5], [-2.0, 0], [-1.5, 0.5], [-0.2, 0.9], [0.5, 0.3]],
        },
        {
            type: 'Destroyer',
            description: 'Heavily armored warship with strong weapons and above-average engines. Built-in Bomb Launcher lets it leave explosive traps in chokepoints.',
            sizeMult: 1.30, cargoCapacity: 1,
            hullMult: 1.4, shieldMult: 0.8, laserMult: 1.2, radarMult: 1.0, engineMult: 1.1,
            builtinModules: ['bomb_launcher'],
            vertices: [[2.2, 0], [1.5, -0.6], [0.4, -1.2], [-0.4, -1.2], [-0.4, -0.6], [-1.5, -0.6], [-2.0, 0], [-1.5, 0.6], [-0.4, 0.6], [-0.4, 1.2], [0.4, 1.2], [1.5, 0.6]],
        },
        {
            type: 'Carrier',
            description: 'Massive command ship with thick armor and shields but minimal firepower. Built-in Drone Bay lets it flood the field with independent combat drones that move, shoot, and expire after 4 turns.',
            sizeMult: 1.60, cargoCapacity: 2,
            hullMult: 2.0, shieldMult: 1.8, laserMult: 0.6, radarMult: 0.7, engineMult: 0.5,
            builtinModules: ['drone_bay'],
            vertices: [[1.0, 0], [0.5, -0.9], [-0.2, -1.7], [-1.2, -1.8], [-2.0, 0], [-1.2, 1.8], [-0.2, 1.7], [0.5, 0.9]],
        },
        {
            type: 'Interceptor',
            description: 'High-speed pursuit vessel built to close distance and disrupt formations. Built-in Tractor Beam can yank enemy ships or asteroids into a collision course.',
            sizeMult: 0.85, cargoCapacity: 1,
            hullMult: 0.7, shieldMult: 1.0, laserMult: 1.0, radarMult: 1.0, engineMult: 1.5,
            builtinModules: ['tractor_beam_emitter'],
            vertices: [[3.0, 0], [0.8, -0.2], [0.0, -0.7], [-1.5, -0.5], [-2.0, 0], [-1.5, 0.5], [0.0, 0.7], [0.8, 0.2]],
        },
        {
            type: 'Drone',
            internal: true,
            description: 'Small expendable combat drone deployed by Carriers. Acts independently each turn — can move and shoot. Expires quietly after 4 turns.',
            sizeMult: 0.60, cargoCapacity: 0,
            hullMult: 1.0, shieldMult: 0, laserMult: 1.0, radarMult: 0.5, engineMult: 1.0,
            builtinModules: [],
            vertices: [[1.5, 0], [0.3, -0.8], [-0.8, -0.5], [-0.8, 0.5], [0.3, 0.8]],
        },
        {
            type: 'Blockade Runner',
            description: 'Quick and elusive, designed to slip through enemy lines. Built-in Flash Emitter can temporarily blind entire groups, letting it strike and vanish.',
            sizeMult: 0.90, cargoCapacity: 1,
            hullMult: 0.75, shieldMult: 0.6, laserMult: 1.0, radarMult: 1.3, engineMult: 1.5,
            builtinModules: ['flash_emitter'],
            vertices: [[2.5, 0], [0.8, -0.5], [-0.5, -1.0], [-1.8, -0.7], [-1.5, 0], [-1.8, 0.7], [-0.5, 1.0], [0.8, 0.5]],
        },
        {
            type: 'Battleship',
            description: 'Colossal capital ship with overwhelming armor, shields, and laser power. Barely moves but hits like a planet. Built-in Target Designator paints enemies for guaranteed laser hits over 3 turns.',
            sizeMult: 1.80, cargoCapacity: 2,
            hullMult: 3.0, shieldMult: 2.5, laserMult: 1.8, radarMult: 1.1, engineMult: 0.35,
            builtinModules: ['mark_module'],
            vertices: [[2.0, 0], [1.5, -0.5], [0.8, -1.5], [-0.2, -1.8], [-1.2, -1.5], [-2.2, -0.8], [-2.5, 0], [-2.2, 0.8], [-1.2, 1.5], [-0.2, 1.8], [0.8, 1.5], [1.5, 0.5]],
        },
        {
            type: 'Jammer',
            description: 'Electronic warfare specialist with exceptional radar and strong shields. Built-in EMP Blaster drains enemy shields and locks all abilities in a wide blast radius.',
            sizeMult: 0.85, cargoCapacity: 1,
            hullMult: 0.9, shieldMult: 1.2, laserMult: 0.85, radarMult: 1.6, engineMult: 1.1,
            builtinModules: ['emp_blast_drive'],
            vertices: [[2.0, 0], [0.5, -0.5], [-0.5, -1.2], [-1.0, -1.5], [-2.0, -0.8], [-2.0, 0.8], [-1.0, 1.5], [-0.5, 1.2], [0.5, 0.5]],
        },
        {
            type: 'Repair Ship',
            description: 'Fleet support vessel with heavy shields and a wide repair cone. Built-in Repair Bay heals all allies in the forward 90° arc each time it fires.',
            sizeMult: 0.85, cargoCapacity: 2,
            hullMult: 1.0, shieldMult: 1.6, laserMult: 0.5, radarMult: 1.0, engineMult: 0.85,
            builtinModules: ['repair_bay'],
            vertices: [[1.5, 0], [0.8, -0.8], [-0.2, -1.2], [-1.8, -1.0], [-2.0, -0.4], [-2.0, 0.4], [-1.8, 1.0], [-0.2, 1.2], [0.8, 0.8]],
        },
        {
            type: 'Hijacker',
            description: 'Small, nimble strike craft built for disruption. Built-in Torpedo Launcher fires self-guided warheads that track the nearest enemy and detonate on contact.',
            sizeMult: 0.75, cargoCapacity: 1,
            hullMult: 0.65, shieldMult: 0.8, laserMult: 0.9, radarMult: 1.2, engineMult: 1.6,
            builtinModules: ['torpedo_launcher'],
            vertices: [[2.0, 0], [0.6, -0.5], [-0.4, -0.9], [-1.2, -0.6], [-1.5, 0], [-1.2, 0.6], [-0.4, 0.9], [0.6, 0.5]],
        },
        {
            type: 'Amplifier',
            description: 'Slow support cruiser wrapped in exceptional shields. Built-in Supercharge Drive fully restores an ally\'s shields and doubles their move, laser damage, and range for a full turn.',
            sizeMult: 0.90, cargoCapacity: 2,
            hullMult: 1.1, shieldMult: 2.2, laserMult: 0.7, radarMult: 1.1, engineMult: 0.65,
            builtinModules: ['supercharge_drive'],
            vertices: [[1.4, 0], [0.8, -0.9], [-0.4, -1.5], [-1.6, -1.1], [-2.2, 0], [-1.6, 1.1], [-0.4, 1.5], [0.8, 0.9]],
        },
        // ── Alien ship types (internal — never sold at stations) ─────────────────
        {
            type: 'Alien Phantom',
            internal: true,
            description: 'Fast alien scout — fragile but extremely agile. Built-in Phase Projector lets it slip into an untargetable phase state to evade attacks.',
            sizeMult: 0.80, cargoCapacity: 0,
            hullMult: 0.75, shieldMult: 0.55, laserMult: 1.1, radarMult: 1.3, engineMult: 1.9,
            builtinModules: ['alien_phase'],
            vertices: [[2.8, 0], [1.2, -0.3], [0.2, -0.8], [-0.8, -1.0], [-2.0, -0.4], [-2.0, 0.4], [-0.8, 1.0], [0.2, 0.8], [1.2, 0.3]],
        },
        {
            type: 'Alien Ravager',
            internal: true,
            description: 'Mid-weight alien fighter with strong lasers and solid engines. Built-in Ravager Beam fires a short-range healing laser — damage dealt restores the Ravager\'s own hull.',
            sizeMult: 1.00, cargoCapacity: 0,
            hullMult: 1.2, shieldMult: 1.0, laserMult: 1.7, radarMult: 1.1, engineMult: 1.2,
            builtinModules: ['alien_ravager'],
            vertices: [[2.2, 0], [0.8, -0.8], [-0.3, -1.5], [-1.5, -1.2], [-2.0, -0.3], [-2.0, 0.3], [-1.5, 1.2], [-0.3, 1.5], [0.8, 0.8]],
        },
        {
            type: 'Alien Titan',
            internal: true,
            description: 'Massive alien dreadnought — nearly indestructible, nearly immobile. Built-in Absorb Array drains hull from all nearby ships to sustain itself in prolonged battles.',
            sizeMult: 1.70, cargoCapacity: 0,
            hullMult: 3.5, shieldMult: 2.8, laserMult: 1.1, radarMult: 0.8, engineMult: 0.4,
            builtinModules: ['alien_absorb'],
            vertices: [[1.2, 0], [0.6, -1.4], [-0.4, -2.2], [-1.8, -2.0], [-2.8, -1.0], [-2.8, 1.0], [-1.8, 2.0], [-0.4, 2.2], [0.6, 1.4]],
        },
        {
            type: 'Alien Stalker',
            internal: true,
            description: 'Long-range alien predator with devastating laser power. Built-in Teleport Core lets it blink to a random position when cornered, making it nearly impossible to pin down.',
            sizeMult: 1.05, cargoCapacity: 0,
            hullMult: 1.05, shieldMult: 0.9, laserMult: 2.1, radarMult: 1.3, engineMult: 1.1,
            builtinModules: ['alien_teleport'],
            vertices: [[3.2, 0], [1.5, -0.6], [0.3, -1.1], [-1.0, -0.8], [-2.2, -0.4], [-2.2, 0.4], [-1.0, 0.8], [0.3, 1.1], [1.5, 0.6]],
        },
        {
            type: 'Alien Queen',
            internal: true,
            description: 'The alien hive mind — a colossal bio-ship of terrifying power. Built-in Stasis Emitter creates zones where ships are frozen in time. Defeating her ends the invasion.',
            sizeMult: 2.20, cargoCapacity: 0,
            hullMult: 8.0, shieldMult: 6.0, laserMult: 3.5, radarMult: 1.6, engineMult: 0.3,
            builtinModules: ['alien_stasis'],
            vertices: [[2.8, 0], [2.0, -1.2], [0.5, -2.5], [-0.8, -2.8], [-2.0, -2.0], [-3.0, -0.8], [-3.5, 0], [-3.0, 0.8], [-2.0, 2.0], [-0.8, 2.8], [0.5, 2.5], [2.0, 1.2]],
        },
        {
            type: 'Swarmlet',
            internal: true,
            description: 'Tiny expendable bio-drone released by an alien swarm ability. Automatically tracks and rams the nearest enemy ship, dying on impact. Expires in 3 turns.',
            sizeMult: 0.35, cargoCapacity: 0,
            hullMult: 1.0, shieldMult: 0, laserMult: 0, radarMult: 0, engineMult: 2.0,
            builtinModules: [],
            vertices: [[1.5, 0], [0, -0.8], [-1.0, 0], [0, 0.8]],
        },
        {
            type: 'Torpedo',
            internal: true,
            description: 'Self-propelled torpedo that tracks the nearest enemy ship and detonates on contact or after 2 turns.',
            sizeMult: 0.30, cargoCapacity: 0,
            hullMult: 1.0, shieldMult: 0, laserMult: 0, radarMult: 0, engineMult: 2.2,
            builtinModules: [],
            vertices: [[2.0, 0], [0.5, -0.3], [-1.0, 0], [0.5, 0.3]],
        },
    ],

    // Faction definitions — each controls fleet color, ship pool, combat behavior, and credit yield
    FACTIONS: [
        {
            id: 'pirates',
            name: 'Pirates',
            description: 'Criminal syndicates raiding shipping lanes for profit. Always hostile on sight. Standard credit bounty on defeat.',
            color: '#ff4444',
            shipTypes: ['Raider', 'Fighter', 'Blockade Runner', 'Destroyer'],
            creditMult: 1,
        },
        {
            id: 'merchants',
            name: 'Merchants',
            description: 'Civilian trading convoys. They fight back if attacked but prefer to flee. Rich cargo means high credit drops.',
            color: '#ffdd44',
            shipTypes: ['Freighter', 'Repair Ship', 'Corvette', 'Amplifier'],
            creditMult: 2,
        },
        {
            id: 'police',
            name: 'Police',
            description: 'System law enforcement. Friendly by default — but attack on sight if you carry an active bounty. Standard credit yield.',
            color: '#4488ff',
            shipTypes: ['Corvette', 'Destroyer', 'Interceptor', 'Fighter', 'Jammer'],
            creditMult: 1,
        },
        {
            id: 'soldiers',
            name: 'Soldiers',
            description: 'Military patrols operating under standing orders. Usually allow passage with a clean record. Very low credit yield.',
            color: '#44ff44',
            shipTypes: ['Corvette', 'Destroyer', 'Fighter'],
            creditMult: 0.25,
        },
        {
            id: 'smugglers',
            name: 'Smugglers',
            description: 'Contraband runners evading law enforcement. Well-armed if cornered. Defeating them yields high credits.',
            color: '#aa44ff',
            shipTypes: ['Blockade Runner', 'Freighter', 'Corvette', 'Scout'],
            creditMult: 2,
        },
        {
            id: 'aliens',
            name: 'Aliens',
            description: 'Unknown entities advancing from deep space. No negotiation possible. Encountered with increasing frequency in outer systems.',
            color: '#ff8800',
            shipTypes: ['Alien Phantom', 'Alien Ravager', 'Alien Titan', 'Alien Stalker'],
            creditMult: 0,
        },
    ],

    // Tiered ship pools per faction — used with fleet strength (low=1-3, mid=4-6, high=7-10)
    FACTION_SHIP_POOLS: {
        pirates:   {
            low:  ['Fighter', 'Blockade Runner'],
            mid:  ['Raider', 'Fighter', 'Blockade Runner'],
            high: ['Raider', 'Destroyer', 'Corvette'],
        },
        merchants: {
            low:  ['Freighter'],
            mid:  ['Freighter', 'Repair Ship', 'Corvette'],
            high: ['Freighter', 'Repair Ship', 'Amplifier', 'Carrier'],
        },
        police:    {
            low:  ['Fighter', 'Corvette'],
            mid:  ['Corvette', 'Destroyer', 'Interceptor'],
            high: ['Destroyer', 'Jammer', 'Battleship', 'Carrier'],
        },
        soldiers:  {
            low:  ['Fighter', 'Corvette'],
            mid:  ['Corvette', 'Destroyer'],
            high: ['Destroyer', 'Battleship', 'Carrier'],
        },
        smugglers: {
            low:  ['Blockade Runner', 'Scout'],
            mid:  ['Blockade Runner', 'Raider', 'Scout'],
            high: ['Blockade Runner', 'Hijacker', 'Raider'],
        },
        aliens:    {
            low:  ['Alien Phantom'],
            mid:  ['Alien Phantom', 'Alien Ravager', 'Alien Stalker'],
            high: ['Alien Ravager', 'Alien Stalker', 'Alien Titan'],
        },
    },
};
