const CONSTANTS_SHIPS = {
    // Stat ranges — midpoint ~10 for laser/engine/radar, ~25 for hull/shields
    SHIP_STATS: {
        HULL_MIN:    40,
        HULL_MAX:    60,
        SHIELDS_MIN: 20,
        SHIELDS_MAX: 30,
        LASER_MIN:    8,
        LASER_MAX:   12,
        RADAR_MIN:    8,
        RADAR_MAX:   12,
        ENGINE_MIN:   8,
        ENGINE_MAX:  12,
    },

    // Ship types: stat multipliers + normalized polygon vertices (pointing +X, scaled by SHIP_SIZE)
    // internal: true types are excluded from station offers and random generation
    SHIP_TYPES: [
        {
            type: 'Fighter',
            description: 'Fast, agile and hits hard, but fragile. Built-in Blink Drive lets it dart across the battlefield in an instant to flank or escape.',
            sizeMult: 0.80,
            hullMult: 0.8, shieldMult: 0.7, laserMult: 1.3, radarMult: 1.1, engineMult: 1.4,
            builtinModules: ['blink_drive'],
            vertices: [[2.2, 0], [0.2, -1.0], [-0.6, -1.4], [-1.2, -0.4], [-1.2, 0.4], [-0.6, 1.4], [0.2, 1.0]],
        },
        {
            type: 'Freighter',
            description: 'Massive armored hauler repurposed for combat. Near-indestructible hull and shields, but painfully slow. Built-in Debris Launcher turns its cargo hold into a scattershot weapon.',
            sizeMult: 1.40,
            hullMult: 1.8, shieldMult: 1.5, laserMult: 0.7, radarMult: 0.8, engineMult: 0.6,
            builtinModules: ['debris_launcher'],
            vertices: [[1.2, 0], [0.8, -1.0], [-0.3, -1.4], [-1.5, -1.2], [-1.5, 1.2], [-0.3, 1.4], [0.8, 1.0]],
        },
        {
            type: 'Raider',
            description: 'Aggressive hit-and-run predator with heavy weapons and strong engines. Built-in Cloak Drive lets it vanish between attacks, striking from the dark.',
            sizeMult: 1.00,
            hullMult: 0.9, shieldMult: 0.6, laserMult: 1.4, radarMult: 1.0, engineMult: 1.3,
            builtinModules: ['cloak_drive'],
            vertices: [[2.3, 0], [0.3, -1.0], [-1.8, -1.5], [-1.3, 0], [-1.8, 1.5], [0.3, 1.0]],
        },
        {
            type: 'Corvette',
            description: 'A well-rounded warship with solid hull, shields, and firepower. The reliable backbone of any fleet — nothing fancy, nothing lacking.',
            sizeMult: 1.10,
            hullMult: 1.2, shieldMult: 1.2, laserMult: 1.0, radarMult: 0.9, engineMult: 0.9,
            builtinModules: [],
            vertices: [[1.8, 0], [1.2, -0.6], [0.4, -1.3], [-0.6, -1.3], [-1.5, -0.5], [-1.5, 0.5], [-0.6, 1.3], [0.4, 1.3], [1.2, 0.6]],
        },
        {
            type: 'Scout',
            description: 'Extreme speed above everything else. Very fragile but nearly impossible to pin down. Built-in Afterburner lets it cross the field in a single burst, damaging anything in its path.',
            sizeMult: 0.75,
            hullMult: 0.6, shieldMult: 0.5, laserMult: 0.8, radarMult: 1.2, engineMult: 1.8,
            builtinModules: ['afterburner_drive'],
            vertices: [[3.0, 0], [0.5, -0.3], [-0.2, -0.9], [-1.5, -0.5], [-2.0, 0], [-1.5, 0.5], [-0.2, 0.9], [0.5, 0.3]],
        },
        {
            type: 'Destroyer',
            description: 'Heavily armored warship with strong weapons and above-average engines. Built-in Bomb Launcher lets it leave explosive traps in chokepoints.',
            sizeMult: 1.30,
            hullMult: 1.4, shieldMult: 0.8, laserMult: 1.2, radarMult: 1.0, engineMult: 1.1,
            builtinModules: ['bomb_launcher'],
            vertices: [[2.2, 0], [1.5, -0.6], [0.4, -1.2], [-0.4, -1.2], [-0.4, -0.6], [-1.5, -0.6], [-2.0, 0], [-1.5, 0.6], [-0.4, 0.6], [-0.4, 1.2], [0.4, 1.2], [1.5, 0.6]],
        },
        {
            type: 'Carrier',
            description: 'Massive command ship with thick armor and shields but minimal firepower. Built-in Drone Bay lets it flood the field with independent combat drones that move, shoot, and expire after 4 turns.',
            sizeMult: 1.60,
            hullMult: 2.0, shieldMult: 1.8, laserMult: 0.6, radarMult: 0.7, engineMult: 0.5,
            builtinModules: ['drone_bay'],
            vertices: [[1.0, 0], [0.5, -0.9], [-0.2, -1.7], [-1.2, -1.8], [-2.0, 0], [-1.2, 1.8], [-0.2, 1.7], [0.5, 0.9]],
        },
        {
            type: 'Interceptor',
            description: 'High-speed pursuit vessel built to close distance and disrupt formations. Built-in Tractor Beam can yank enemy ships or asteroids into a collision course.',
            sizeMult: 0.85,
            hullMult: 0.7, shieldMult: 1.0, laserMult: 1.0, radarMult: 1.0, engineMult: 1.5,
            builtinModules: ['tractor_beam_emitter'],
            vertices: [[3.0, 0], [0.8, -0.2], [0.0, -0.7], [-1.5, -0.5], [-2.0, 0], [-1.5, 0.5], [0.0, 0.7], [0.8, 0.2]],
        },
        {
            type: 'Drone',
            internal: true,
            description: 'Small expendable combat drone deployed by Carriers. Acts independently each turn — can move and shoot. Expires quietly after 4 turns.',
            sizeMult: 0.60,
            hullMult: 1.0, shieldMult: 0, laserMult: 1.0, radarMult: 0.5, engineMult: 1.0,
            builtinModules: [],
            vertices: [[1.5, 0], [0.3, -0.8], [-0.8, -0.5], [-0.8, 0.5], [0.3, 0.8]],
        },
        {
            type: 'Smuggler',
            description: 'Quick and elusive, designed to slip through enemy lines. Built-in Flash Emitter can temporarily blind entire groups, letting it strike and vanish.',
            sizeMult: 0.90,
            hullMult: 0.75, shieldMult: 0.6, laserMult: 1.0, radarMult: 1.3, engineMult: 1.5,
            builtinModules: ['flash_emitter'],
            vertices: [[2.5, 0], [0.8, -0.5], [-0.5, -1.0], [-1.8, -0.7], [-1.5, 0], [-1.8, 0.7], [-0.5, 1.0], [0.8, 0.5]],
        },
        {
            type: 'Battleship',
            description: 'Colossal capital ship with overwhelming armor, shields, and laser power. Barely moves but hits like a planet. Built-in Target Designator paints enemies for guaranteed laser hits over 3 turns.',
            sizeMult: 1.80,
            hullMult: 3.0, shieldMult: 2.5, laserMult: 1.8, radarMult: 1.1, engineMult: 0.35,
            builtinModules: ['mark_module'],
            vertices: [[2.0, 0], [1.5, -0.5], [0.8, -1.5], [-0.2, -1.8], [-1.2, -1.5], [-2.2, -0.8], [-2.5, 0], [-2.2, 0.8], [-1.2, 1.5], [-0.2, 1.8], [0.8, 1.5], [1.5, 0.5]],
        },
        {
            type: 'Jammer',
            description: 'Electronic warfare specialist with exceptional radar and strong shields. Built-in EMP Blaster drains enemy shields and locks all abilities in a wide blast radius.',
            sizeMult: 0.85,
            hullMult: 0.9, shieldMult: 1.2, laserMult: 0.85, radarMult: 1.6, engineMult: 1.1,
            builtinModules: ['emp_blast_drive'],
            vertices: [[2.0, 0], [0.5, -0.5], [-0.5, -1.2], [-1.0, -1.5], [-2.0, -0.8], [-2.0, 0.8], [-1.0, 1.5], [-0.5, 1.2], [0.5, 0.5]],
        },
        {
            type: 'Repair Ship',
            description: 'Fleet support vessel with heavy shields and a wide repair cone. Built-in Repair Bay heals all allies in the forward 90° arc each time it fires.',
            sizeMult: 0.85,
            hullMult: 1.0, shieldMult: 1.6, laserMult: 0.5, radarMult: 1.0, engineMult: 0.85,
            builtinModules: ['repair_bay'],
            vertices: [[1.5, 0], [0.8, -0.8], [-0.2, -1.2], [-1.8, -1.0], [-2.0, -0.4], [-2.0, 0.4], [-1.8, 1.0], [-0.2, 1.2], [0.8, 0.8]],
        },
        {
            type: 'Disruptor',
            description: 'Small, nimble electronic warfare craft built around its Hack Module. Weak in a straight fight but devastating at turning enemy ships against each other.',
            sizeMult: 0.75,
            hullMult: 0.65, shieldMult: 0.8, laserMult: 0.9, radarMult: 1.2, engineMult: 1.6,
            builtinModules: ['hack_module'],
            vertices: [[2.0, 0], [0.6, -0.5], [-0.4, -0.9], [-1.2, -0.6], [-1.5, 0], [-1.2, 0.6], [-0.4, 0.9], [0.6, 0.5]],
        },
        {
            type: 'Amplifier',
            description: 'Slow support cruiser wrapped in exceptional shields. Built-in Supercharge Drive fully restores an ally\'s shields and doubles their move, laser damage, and range for a full turn.',
            sizeMult: 0.90,
            hullMult: 1.1, shieldMult: 2.2, laserMult: 0.7, radarMult: 1.1, engineMult: 0.65,
            builtinModules: ['supercharge_drive'],
            vertices: [[1.4, 0], [0.8, -0.9], [-0.4, -1.5], [-1.6, -1.1], [-2.2, 0], [-1.6, 1.1], [-0.4, 1.5], [0.8, 0.9]],
        },
        // ── Alien ship types (internal — never sold at stations) ─────────────────
        {
            type: 'Alien Phantom',
            internal: true,
            description: 'Fast alien scout — fragile but extremely agile.',
            sizeMult: 0.80,
            hullMult: 0.55, shieldMult: 0.35, laserMult: 0.85, radarMult: 1.2, engineMult: 1.9,
            builtinModules: [],
            vertices: [[2.8, 0], [1.2, -0.3], [0.2, -0.8], [-0.8, -1.0], [-2.0, -0.4], [-2.0, 0.4], [-0.8, 1.0], [0.2, 0.8], [1.2, 0.3]],
        },
        {
            type: 'Alien Ravager',
            internal: true,
            description: 'Mid-weight alien fighter with strong lasers and solid engines.',
            sizeMult: 1.00,
            hullMult: 0.9, shieldMult: 0.75, laserMult: 1.4, radarMult: 1.0, engineMult: 1.2,
            builtinModules: [],
            vertices: [[2.2, 0], [0.8, -0.8], [-0.3, -1.5], [-1.5, -1.2], [-2.0, -0.3], [-2.0, 0.3], [-1.5, 1.2], [-0.3, 1.5], [0.8, 0.8]],
        },
        {
            type: 'Alien Titan',
            internal: true,
            description: 'Massive alien dreadnought — nearly indestructible, nearly immobile.',
            sizeMult: 1.70,
            hullMult: 2.5, shieldMult: 2.0, laserMult: 0.9, radarMult: 0.7, engineMult: 0.4,
            builtinModules: [],
            vertices: [[1.2, 0], [0.6, -1.4], [-0.4, -2.2], [-1.8, -2.0], [-2.8, -1.0], [-2.8, 1.0], [-1.8, 2.0], [-0.4, 2.2], [0.6, 1.4]],
        },
        {
            type: 'Alien Stalker',
            internal: true,
            description: 'Long-range alien predator with devastating laser power.',
            sizeMult: 1.05,
            hullMult: 0.8, shieldMult: 0.65, laserMult: 1.6, radarMult: 1.1, engineMult: 1.1,
            builtinModules: [],
            vertices: [[3.2, 0], [1.5, -0.6], [0.3, -1.1], [-1.0, -0.8], [-2.2, -0.4], [-2.2, 0.4], [-1.0, 0.8], [0.3, 1.1], [1.5, 0.6]],
        },
        {
            type: 'Alien Queen',
            internal: true,
            description: 'The alien hive mind — a colossal bio-ship of terrifying power. Defeating her ends the invasion.',
            sizeMult: 1.50,
            hullMult: 4.5, shieldMult: 3.5, laserMult: 2.2, radarMult: 1.4, engineMult: 0.3,
            builtinModules: [],
            vertices: [[2.8, 0], [2.0, -1.2], [0.5, -2.5], [-0.8, -2.8], [-2.0, -2.0], [-3.0, -0.8], [-3.5, 0], [-3.0, 0.8], [-2.0, 2.0], [-0.8, 2.8], [0.5, 2.5], [2.0, 1.2]],
        },
    ],

    // Faction definitions — each controls fleet color, ship pool, combat behavior, and credit yield
    FACTIONS: [
        {
            id: 'pirates',
            name: 'Pirates',
            color: '#ff4444',
            shipTypes: ['Raider', 'Fighter', 'Smuggler', 'Destroyer'],
            creditMult: 1,
        },
        {
            id: 'merchants',
            name: 'Merchants',
            color: '#ffdd44',
            shipTypes: ['Freighter', 'Repair Ship', 'Corvette', 'Amplifier'],
            creditMult: 2,
        },
        {
            id: 'police',
            name: 'Police',
            color: '#4488ff',
            shipTypes: ['Corvette', 'Destroyer', 'Interceptor', 'Fighter', 'Jammer'],
            creditMult: 1,
        },
        {
            id: 'soldiers',
            name: 'Soldiers',
            color: '#44ff44',
            shipTypes: ['Corvette', 'Destroyer', 'Fighter'],
            creditMult: 0.25,
        },
        {
            id: 'smugglers',
            name: 'Smugglers',
            color: '#aa44ff',
            shipTypes: ['Smuggler', 'Freighter', 'Corvette', 'Scout'],
            creditMult: 2,
        },
        {
            id: 'aliens',
            name: 'Aliens',
            color: '#ff8800',
            shipTypes: ['Alien Phantom', 'Alien Ravager', 'Alien Titan', 'Alien Stalker'],
            creditMult: 0,
            routeSpawn: false, // not placed by generateEncountersForRoute
        },
    ],
};
